---
abstract: 'Dist::Zilla plugin bundle used by RAYM'
author:
  - 'Ray Miller'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300017, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-RAYM
requires:
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-Author-RAYM
  homepage: https://github.com/ray1729/Dist-Zilla-PluginBundle-Author-RAYM/wiki
  repository: git://github.com/ray1729/Dist-Zilla-PluginBundle-Author-RAYM.git
version: 0.001
